services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    branch: main
    repo: https://github.com/Mkpo1234/Hhhyu
    autoDeploy: true
